### ISSUE TITLE
Not able to set color on shapes

### ISSUE THREAD

**Issue by redbeardmickey** [opencolor-tools/opencolor-tools#7]
When I select a shape layer and go to Plugins > Open Color > Set Color, nothing happens. The dialog window doesn't show up. It works when I set color on text.

I am running Sketch 46.2.

**Comment by MDBas** [comment]
+1

**Comment by halfbyte** [comment]
Guys, the right place to report bugs is on the opencolor-tools/sketch-opencolor repo, but as you can see, I've created an issue there already. I'll leave this open nevertheless. We'll try to figure this out. I'm assuming Sketch changed the internal API we've been using (again).

Sorry for the delay.

**Comment by halfbyte** [comment]
Hey, @MDBas, @redbeardmickey could you hop over to [the latest beta release](https://github.com/opencolor-tools/sketch-opencolor/releases/tag/v1.8.7-beta.1) of the plugin and tell me if that version works for you? Did a quick fix but I am unsure if I broke something else (don't have too much time to thoroughly test this so any help is appreciated).

**Comment by MDBas** [comment]
Works for me! Thanks

**Comment by redbeardmickey** [comment]
Works for me too. Thanks!

**Comment by halfbyte** [comment]
Ok, I'll try to cut a new full Open Color Tools release next week that will contain this fix. If you find any other bugs with the beta in the meantime, let me know. (Preferably on the correct project :)
