### ISSUE TITLE
Cannot import ACO

### ISSUE THREAD

**Issue by ColinLondon** [opencolor-tools/opencolor-tools#8]
First issue: 

Open File > Import and all files except ACO are greyed out.

Second issue:

Drag ACO file to an existing palette and nothing is imported. It is left blank.

**Comment by halfbyte** [comment]
@cpshanley Thanks for the report. If I recall correctly, Import only works on OCO files - It's not really well named. 

If you drag and drop an ACO file it will always get you to the import dialog, but my tests seem to suggest that the import is indeed broken.

Could you attach a small example ACO file here that fails to import and what colors it should contain? That way we can build a test case that I can work against. My suspicion would be that it has to do with the used color space, but I'll need to investigate more.

Pinging @rockitbaby - Do you have a minute to look at this?
